-- 011_launch_seed_content.sql
-- Serious launch seed polls so the public surface feels credible immediately.

with topic_ids as (
  select slug, id from public.topics
  where slug in ('climate', 'econ', 'geopol', 'health', 'science', 'tech', 'energy', 'elect', 'local')
), seed_polls(topic_slug, question, region, options, source_of_truth, resolution_criteria, cutoff_at, resolves_at) as (
  values
  ('geopol', 'Will the European Council formally open accession negotiations with Ukraine on all negotiation clusters before 31 December 2026?', 'European Union / Ukraine', '["Yes", "No"]', 'European Council conclusions and European Commission enlargement package publications', 'Resolves YES if official European Council conclusions or Commission enlargement documentation state that accession negotiations with Ukraine have opened on all negotiation clusters by 2026-12-31 23:59 UTC. Draft agendas, leaks, and press speculation do not count.', '2026-12-20 23:59:00+00', '2027-01-08 23:59:00+00'),
  ('econ', 'Will the ECB lower its deposit facility rate at least twice during calendar year 2026?', 'Euro area', '["Yes", "No"]', 'European Central Bank monetary policy decisions page', 'Resolves YES if ECB official monetary policy decisions record at least two decreases in the deposit facility rate with decision dates from 2026-01-01 through 2026-12-31 inclusive. Intra-meeting market pricing and speeches do not count.', '2026-12-18 23:59:00+00', '2027-01-08 23:59:00+00'),
  ('climate', 'Will the EU publish its final 2040 climate target legislation in the Official Journal before 30 June 2026?', 'European Union', '["Yes", "No"]', 'Official Journal of the European Union and EUR-Lex', 'Resolves YES if final adopted legislation setting the EU 2040 climate target is published in the Official Journal or EUR-Lex by 2026-06-30 23:59 UTC. Commission proposals, Council positions, and trilogue reports do not count as final publication.', '2026-06-20 23:59:00+00', '2026-07-08 23:59:00+00'),
  ('health', 'Will WHO declare a new Public Health Emergency of International Concern before 31 December 2026?', 'Global', '["Yes", "No"]', 'World Health Organization official Director-General statements and WHO emergency page', 'Resolves YES if the WHO Director-General formally declares a new PHEIC with an announcement dated on or before 2026-12-31. Continuations or extensions of existing PHEICs do not count unless WHO identifies a new emergency declaration.', '2026-12-24 23:59:00+00', '2027-01-08 23:59:00+00'),
  ('elect', 'Will turnout in the 2026 United States midterm House elections exceed 50% of the voting-eligible population?', 'United States', '["Yes", "No"]', 'United States Elections Project national turnout statistics', 'Resolves YES if the United States Elections Project reports national 2026 House midterm turnout above 50.0% of voting-eligible population. Preliminary media estimates do not count; use the first published national post-election dataset from the named source.', '2026-11-03 23:59:00+00', '2026-12-15 23:59:00+00'),
  ('geopol', 'Will the UN Security Council adopt a resolution explicitly authorizing a new peacekeeping mission before 31 December 2026?', 'United Nations', '["Yes", "No"]', 'United Nations Security Council official resolutions database', 'Resolves YES if a Security Council resolution adopted by 2026-12-31 explicitly authorizes creation of a new UN peacekeeping mission. Mandate renewals, statements, and failed draft resolutions do not count.', '2026-12-24 23:59:00+00', '2027-01-08 23:59:00+00'),
  ('tech', 'Will the EU AI Office publish a public GPAI model code-of-practice compliance assessment before 1 October 2026?', 'European Union', '["Yes", "No"]', 'EU AI Office official publications and European Commission digital strategy pages', 'Resolves YES if the EU AI Office or European Commission publishes a public compliance assessment or equivalent formal evaluation of at least one general-purpose AI model/code-of-practice process before 2026-10-01 00:00 UTC. Speeches, consultations, and draft templates do not count.', '2026-09-20 23:59:00+00', '2026-10-08 23:59:00+00'),
  ('econ', 'Will UK CPI inflation be at or below 2.0% in any ONS monthly release published before 31 December 2026?', 'United Kingdom', '["Yes", "No"]', 'UK Office for National Statistics CPI release table', 'Resolves YES if any ONS CPI release published before 2026-12-31 reports annual CPI inflation at or below 2.0%. Later revisions do not change the result unless the original release is withdrawn.', '2026-12-15 23:59:00+00', '2027-01-08 23:59:00+00')
)
insert into public.polls (topic_id, question, region, options, source_of_truth, resolution_criteria, cutoff_at, resolves_at, status)
select t.id, s.question, s.region, s.options::jsonb, s.source_of_truth, s.resolution_criteria, s.cutoff_at::timestamptz, s.resolves_at::timestamptz, 'active'
from seed_polls s
join topic_ids t on t.slug = s.topic_slug
where not exists (select 1 from public.polls p where p.question = s.question);
